# docker-compose.yml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ramonov-1.0.0:dev
    container_name: ramonov
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      JAVA_OPTS: "-Xms256m -Xmx512m"
      TZ: "America/Sao_Paulo"
      # Exemplos de vari√°veis do Spring:
      # SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/minha_base"
      # SPRING_DATASOURCE_USERNAME: "user"
      # SPRING_DATASOURCE_PASSWORD: "secret"
    # depends_on:
    #   - db

  # Exemplo de Postgres (descomente se precisar)
  # db:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: "user"
  #     POSTGRES_PASSWORD: "secret"
  #     POSTGRES_DB: "minha_base"
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
